"""Morning report generator (workplan v6 Step 4).

Pulls live state from Supabase + the most recent run-stats artifact, writes
a Markdown summary to ``artifacts/overnight-report-<date>.md``.
"""

from __future__ import annotations

import json
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from rich.console import Console

from ..db import REPO_ROOT, connect

console = Console()


@dataclass
class Counts:
    vcs_total: int = 0
    vcs_with_careers: int = 0
    jobs_total: int = 0
    jobs_active: int = 0
    jobs_inactive: int = 0
    by_source: dict[str, int] = field(default_factory=dict)
    by_category: dict[str, int] = field(default_factory=dict)
    by_company: list[tuple[str, int]] = field(default_factory=list)


def _scalar(value: Any) -> int:
    return int(value) if value is not None else 0


def _latest_run_stats(artifacts: Path) -> dict[str, Any] | None:
    candidates = sorted(artifacts.glob("run-stats-*.json"))
    if not candidates:
        return None
    raw: Any = json.loads(candidates[-1].read_text(encoding="utf-8"))
    return raw if isinstance(raw, dict) else None


def _query_counts() -> Counts:
    counts = Counts()
    with connect() as conn, conn.cursor() as cur:
        cur.execute("select count(*) from vcs;")
        row = cur.fetchone()
        counts.vcs_total = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from vcs where careers_url is not null and careers_url <> '';")
        row = cur.fetchone()
        counts.vcs_with_careers = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from jobs;")
        row = cur.fetchone()
        counts.jobs_total = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from jobs where is_active = true;")
        row = cur.fetchone()
        counts.jobs_active = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from jobs where is_active = false;")
        row = cur.fetchone()
        counts.jobs_inactive = _scalar(row[0]) if row else 0
        cur.execute(
            "select ats_source, count(*) from jobs where is_active = true group by ats_source;"
        )
        counts.by_source = {str(s): int(c) for s, c in cur.fetchall()}
        cur.execute(
            "select role_category, count(*) from jobs where is_active = true group by role_category;"
        )
        counts.by_category = {(str(s) if s else "tier2_pending"): int(c) for s, c in cur.fetchall()}
        cur.execute(
            "select company_name, count(*) from jobs where is_active = true "
            "group by company_name order by 2 desc;"
        )
        counts.by_company = [(str(c), int(n)) for c, n in cur.fetchall()]
    return counts


def _list_invalid_quarantine(artifacts: Path) -> list[tuple[str, int]]:
    out: list[tuple[str, int]] = []
    for path in sorted(artifacts.glob("invalid_jobs_*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            count = len(data) if isinstance(data, list) else 0
        except (json.JSONDecodeError, OSError):
            count = -1
        out.append((path.name, count))
    return out


def main() -> int:
    artifacts = REPO_ROOT / "artifacts"
    counts = _query_counts()
    run = _latest_run_stats(artifacts)
    invalid = _list_invalid_quarantine(artifacts)
    today = time.strftime("%Y-%m-%d", time.gmtime())
    out_path = artifacts / f"overnight-report-{today.replace('-', '')}.md"

    lines: list[str] = []
    lines.append(f"# Career-Buddy overnight report — {today}\n")
    lines.append("Layer-1 first-run synthesis. Generated by `career_buddy_scraper.cli.report`.\n\n")

    lines.append("## Headline numbers\n")
    lines.append(f"- VCs in master list      : **{counts.vcs_total}**")
    lines.append(f"- VCs with `careers_url`  : **{counts.vcs_with_careers}**")
    lines.append(f"- Jobs total (all-time)   : **{counts.jobs_total}**")
    lines.append(f"- Jobs active             : **{counts.jobs_active}**")
    lines.append(f"- Jobs inactive           : **{counts.jobs_inactive}**\n")

    lines.append("## Active jobs by ATS source\n")
    for src, n in sorted(counts.by_source.items()):
        lines.append(f"- `{src}`: {n}")
    lines.append("")

    lines.append("## Active jobs by role-category (Tier-1 regex)\n")
    for cat, n in sorted(counts.by_category.items()):
        lines.append(f"- `{cat}`: {n}")
    lines.append("")

    lines.append("## Active jobs by company\n")
    for company, n in counts.by_company:
        lines.append(f"- {company}: {n}")
    lines.append("")

    if run is not None:
        stats = run.get("stats", {})
        if isinstance(stats, dict):
            lines.append("## Most recent run stats\n")
            lines.append(f"- Started UTC      : {run.get('timestamp_utc')}")
            duration_s = stats.get("duration_s")
            duration_str = f"{duration_s:.1f}s" if isinstance(duration_s, (int, float)) else "n/a"
            lines.append(f"- Duration         : {duration_str}")
            lines.append(
                f"- VCs matched      : {stats.get('vcs_matched')}/{stats.get('vcs_total')}"
            )
            lines.append(f"- VCs unmatched    : {stats.get('vcs_unmatched')}")
            lines.append(f"- Rows fetched     : {stats.get('rows_fetched')}")
            lines.append(f"- Rows valid       : {stats.get('rows_valid')}")
            lines.append(f"- Rows invalid     : {stats.get('rows_invalid')}")
            lines.append(f"- Inserted         : {stats.get('inserted')}")
            lines.append(f"- Updated          : {stats.get('updated')}")
            lines.append(f"- Marked stale     : {stats.get('affected_stale')}")
            lines.append("")
        limiter = run.get("limiter_metrics", {})
        if isinstance(limiter, dict):
            lines.append("## HTTP limiter metrics (most recent run)\n")
            lines.append(f"- Total requests   : {limiter.get('total_requests')}")
            lines.append(f"- Cache hits       : {limiter.get('cache_hits')}")
            lines.append(f"- Peak req/min     : {limiter.get('peak_per_minute')}")
            by_method = limiter.get("by_method", {})
            by_status = limiter.get("by_status", {})
            lines.append(
                f"- By method        : {dict(sorted(by_method.items())) if isinstance(by_method, dict) else 'n/a'}"
            )
            lines.append(
                f"- By status        : {dict(sorted(by_status.items())) if isinstance(by_status, dict) else 'n/a'}"
            )
            lines.append("")
        errors = run.get("errors", [])
        if isinstance(errors, list) and errors:
            lines.append("## Errors\n")
            for err in errors:
                lines.append(f"- {err}")
            lines.append("")

    if invalid:
        lines.append("## Invalid-jobs quarantine\n")
        for fname, n in invalid:
            lines.append(f"- `{fname}`: {n} rows")
        lines.append("")
    else:
        lines.append(
            "## Invalid-jobs quarantine\n\nNo quarantine artifacts produced — every fetched row passed Pydantic validation.\n"
        )

    lines.append("## Yield-gate analysis\n")
    active = counts.jobs_active
    lines.append(f"- Active jobs in DB: **{active}**")
    if active >= 30:
        lines.append("- Yield-gate: **MET** (≥ 30 active jobs).")
    else:
        lines.append(f"- Yield-gate: **shortfall** (target ≥ 30, observed {active}).")
        lines.append(
            "- Workplan v6 fallback path: shortfall is documented here "
            "AND `jobs_inserted_or_updated > 0` (the first run inserted 158 rows; "
            "141 were deactivated as Notion Labs / Notion Capital VC contamination)."
        )
    lines.append("")

    specific_total = sum(
        n for cat, n in counts.by_category.items() if cat != "tier2_pending"
    )
    pending_total = counts.by_category.get("tier2_pending", 0)
    coverage_pct = (
        (specific_total / counts.jobs_active * 100.0) if counts.jobs_active else 0.0
    )
    top_companies = ", ".join(f"{c} ({n})" for c, n in counts.by_company[:5])
    ats_summary = ", ".join(
        f"{src} {n}" for src, n in sorted(counts.by_source.items(), key=lambda kv: -kv[1])
    )

    lines.append("## Findings\n")
    lines.append(
        f"1. **Coverage at scale.** {counts.vcs_total} VCs in master list, "
        f"{counts.jobs_active} active jobs across {ats_summary}. Top employers: "
        f"{top_companies}. After three discover_slugs rounds + manual pins, the "
        "VC + portfolio-company funnel is the real volume source — direct VC hires "
        "remain a tiny minority of total rows."
    )
    lines.append(
        f"2. **Tier-1 regex coverage = {specific_total}/{counts.jobs_active} "
        f"({coverage_pct:.0f}%).** Specific buckets: "
        + ", ".join(
            f"{cat} {n}"
            for cat, n in sorted(
                ((c, n) for c, n in counts.by_category.items() if c != "tier2_pending"),
                key=lambda kv: -kv[1],
            )
        )
        + f". Remaining {pending_total} rows still NULL. Tier-2 Gemini classifier "
        "mops these up daily but is gated by Free-Tier 20 RPD on gemini-2.5-flash."
    )
    lines.append(
        "3. **Systematic out-of-scope blacklist via `vcs.skip_probe`.** Migration "
        "0007 introduced the flag for VCs whose ATS embed cannot be scraped via "
        "public API (Ashby private boards, Zoho Recruit, JS-only renders). Initial "
        "blacklist: `11x.ai`, `500.co`. Every recurring 404/quota-loss should "
        "either be pinned via `vc_overrides`, fixed via adapter expansion (≥3 VCs "
        "needed before adding one), or marked skip_probe — never tolerated as "
        "permanent error noise."
    )
    lines.append(
        "4. **Greenhouse `boards-api` slug collision (fixed).** Bare-subdomain "
        "regex `(?P<slug>[a-z0-9-]+)\\.greenhouse\\.io` was matching "
        "`boards-api.greenhouse.io` and capturing `boards-api` as a slug, "
        "producing fake (provider=greenhouse, slug=boards-api) errors for any "
        "careers page that referenced the Greenhouse API URL (anduril.com, "
        "glean.com). Fix in commit `c6442bd`: explicit `boards-api` pattern + "
        "negative-lookahead for reserved subdomains. Two regression tests added."
    )
    lines.append(
        "5. **Tier-2 quota economics.** Free Tier `gemini-2.5-flash` = 20 RPD. "
        "500 titles/batch ⇒ ~20 batches per ~10k pending rows ⇒ exactly one full "
        "sweep per quota window. Schedule classify_tier2 daily after the 09:00 "
        "CEST quota reset (cron `0 7 * * *` UTC)."
    )
    lines.append("")

    lines.append("## Recommended next actions\n")
    lines.append(
        "1. **Multi-page HTML-discovery.** `discover_ats` only scans `careers_url`. "
        "Extending to `/jobs`, `/about`, `/team` (+ iframe/script-src introspection) "
        "would unlock VCs that hide their ATS embed off the main careers page "
        "(11x.ai is the canonical case)."
    )
    lines.append(
        "2. **`vc_overrides` table.** Direct-ATS slug pinning when the auto-"
        "discovered slug differs from reality (e.g. Notion Capital vs Notion Labs "
        "collision). Cheaper and more auditable than amending discover_slugs "
        "heuristics for every new edge case."
    )
    lines.append(
        "3. **Defer Zoho Recruit adapter.** Only 500.co needs it today; rule is "
        "≥3 VCs before adding a new adapter. Re-evaluate when discover_slugs "
        "round-N surfaces more Zoho boards."
    )
    lines.append(
        "4. **Schema add: `posted_by_vc TEXT`.** Portfolio-recruiting boards "
        "(Cherry's `talent.cherry.vc`, Speedinvest's similar talent-redirection) "
        "currently conflate the hiring company with the VC firm. Adding the "
        "column lets us model both relationships cleanly."
    )
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    console.print(f"[green]wrote {out_path}[/green]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
